"use client";

import { useEffect, useState } from "react";
import { Landmark } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { CollapsibleCard } from "@/components/ui/collapsible-card";
import { CHF_STEP, NUM_STEP } from "@/components/shared/numeric-steps";
import {
  ChfStepperInput,
  PercentStepperNumberInput,
  StepperButtons,
} from "@/components/shared/stepper-inputs";
import {
  formatCHF,
  PILLAR_3A_MIN_WITHDRAWAL_OFFSET,
  PILLAR_3A_MAX_WITHDRAWAL_OFFSET,
  clampPillar3aWithdrawalOffset,
  pillar3aWithdrawalOffsetBounds,
  type Pillar3aResult,
  type ProfileForScenario,
  type ScenarioOverrides,
} from "@/lib/engine";
import { formatSwissNumber, parseSwissNumber } from "@/lib/format/numbers";
import { defaultWithdrawalSchedule, spreadUniqueWithdrawalOffsets } from "@/lib/pillar3a/accounts";
import { profileRateToPercent } from "@/lib/scenarios/profile";
import {
  PERSON1_COLOR,
  PERSON2_COLOR,
} from "@/lib/household/person-colors";

export type Pillar3aEffectiveAccount = {
  id: string;
  name: string;
  currentCapital: number;
  annualContribution: number;
  returnRate?: number | null;
  isAutoGenerated?: boolean;
};

export type Pillar3aAccountOverrideState = {
  withdrawalYearOffset: number;
  useCapitalOverride: boolean;
  capitalOverride: string;
  useContributionOverride: boolean;
  contributionOverride: string;
  useReturnOverride: boolean;
  returnOverride: number;
};

function effectiveAccountsFromResult(
  profile: ProfileForScenario,
  result: Pillar3aResult,
): Pillar3aEffectiveAccount[] {
  if (result.accounts.length > 0) {
    return result.accounts.map((account) => {
      const profileAccount = profile.pillar3aAccounts?.find(
        (a) => a.id === account.id,
      );
      return {
        id: account.id,
        name: account.name,
        currentCapital: profileAccount?.currentCapital ?? 0,
        annualContribution: account.annualContribution,
        returnRate: account.returnRate,
        isAutoGenerated: account.isAutoGenerated,
      };
    });
  }
  return (profile.pillar3aAccounts ?? []).map((a) => ({
    id: a.id,
    name: a.name,
    currentCapital: a.currentCapital,
    annualContribution: a.annualContribution,
    returnRate: a.returnRate,
  }));
}

export function buildInitialPillar3aOverrides(
  profile: ProfileForScenario,
  savedPillar3a?: ScenarioOverrides["pillar3a"],
  effectiveAccounts?: Pillar3aEffectiveAccount[],
  scheduleOptions?: {
    bvgPensionStartAge: number;
    earliestWithdrawalAge: number;
    latestWithdrawalAge?: number;
  },
): Record<string, Pillar3aAccountOverrideState> {
  const accounts = effectiveAccounts ?? profile.pillar3aAccounts ?? [];
  const savedSchedule = { ...savedPillar3a?.withdrawalSchedule };

  for (const account of accounts) {
    const legacy = savedPillar3a?.accountOverrides?.[account.id] as
      | { withdrawalYearOffsetOverride?: number | null }
      | undefined;
    if (
      savedSchedule[account.id] == null &&
      legacy?.withdrawalYearOffsetOverride != null
    ) {
      savedSchedule[account.id] = legacy.withdrawalYearOffsetOverride;
    }
  }

  const schedule = defaultWithdrawalSchedule(
    accounts.map((a) => a.id),
    savedSchedule,
    scheduleOptions,
  );
  const offsetBounds =
    scheduleOptions?.bvgPensionStartAge != null &&
    scheduleOptions?.earliestWithdrawalAge != null
      ? pillar3aWithdrawalOffsetBounds(
          scheduleOptions.bvgPensionStartAge,
          scheduleOptions.earliestWithdrawalAge,
          scheduleOptions.latestWithdrawalAge ??
            scheduleOptions.bvgPensionStartAge,
          PILLAR_3A_MIN_WITHDRAWAL_OFFSET,
          PILLAR_3A_MAX_WITHDRAWAL_OFFSET,
        )
      : null;
  const result: Record<string, Pillar3aAccountOverrideState> = {};

  for (const account of accounts) {
    const ov = savedPillar3a?.accountOverrides?.[account.id];
    const accountReturnPercent = profileRateToPercent(account.returnRate, 0.03);
    const rawOffset = schedule[account.id] ?? 0;
    result[account.id] = {
      withdrawalYearOffset:
        offsetBounds != null
          ? clampPillar3aWithdrawalOffset(rawOffset, offsetBounds)
          : rawOffset,
      useCapitalOverride: ov?.currentCapitalOverride != null,
      capitalOverride: formatSwissNumber(
        ov?.currentCapitalOverride ?? account.currentCapital,
      ),
      useContributionOverride: ov?.annualContributionOverride != null,
      contributionOverride: formatSwissNumber(
        ov?.annualContributionOverride ?? account.annualContribution,
      ),
      useReturnOverride: ov?.returnRateOverride != null,
      returnOverride: ov?.returnRateOverride ?? accountReturnPercent,
    };
  }

  return result;
}

export function pillar3aOverridesToScenario(
  profile: ProfileForScenario,
  state: Record<string, Pillar3aAccountOverrideState>,
  effectiveAccounts?: Pillar3aEffectiveAccount[],
  offsetBounds?: { min: number; max: number },
): ScenarioOverrides["pillar3a"] | undefined {
  const accounts = effectiveAccounts ?? profile.pillar3aAccounts ?? [];
  if (accounts.length === 0) return undefined;

  const bounds =
    offsetBounds ??
    ({
      min: PILLAR_3A_MIN_WITHDRAWAL_OFFSET,
      max: PILLAR_3A_MAX_WITHDRAWAL_OFFSET,
    } as const);

  const withdrawalSchedule: Record<string, number> = {};
  const accountOverrides: NonNullable<
    ScenarioOverrides["pillar3a"]
  >["accountOverrides"] = {};

  for (const [index, account] of accounts.entries()) {
    const item = state[account.id];
    const defaultOffset =
      offsetBounds != null
        ? spreadUniqueWithdrawalOffsets(
            accounts.length,
            offsetBounds.min,
            offsetBounds.max,
          )[index] ?? index
        : index;

    withdrawalSchedule[account.id] = clampPillar3aWithdrawalOffset(
      item?.withdrawalYearOffset ?? defaultOffset,
      bounds,
    );

    if (!item) continue;

    const hasValueOverride =
      item.useCapitalOverride ||
      item.useContributionOverride ||
      item.useReturnOverride;

    if (hasValueOverride) {
      accountOverrides[account.id] = {
        currentCapitalOverride: item.useCapitalOverride
          ? parseSwissNumber(item.capitalOverride)
          : null,
        annualContributionOverride: item.useContributionOverride
          ? parseSwissNumber(item.contributionOverride)
          : null,
        returnRateOverride: item.useReturnOverride ? item.returnOverride : null,
      };
    }
  }

  return {
    withdrawalSchedule,
    accountOverrides:
      Object.keys(accountOverrides).length > 0 ? accountOverrides : undefined,
  };
}

export function ScenarioPillar3aSection({
  profile,
  result,
  overrideState,
  onChange,
  person = "primary",
  embedded = false,
}: {
  profile: ProfileForScenario;
  result: Pillar3aResult;
  overrideState: Record<string, Pillar3aAccountOverrideState>;
  onChange: (
    accountId: string,
    patch: Partial<Pillar3aAccountOverrideState>,
  ) => void;
  person?: "primary" | "partner";
  /** Ohne äusseres Card-Wrapper (für Split-Layout) */
  embedded?: boolean;
}) {
  const displayAccounts = effectiveAccountsFromResult(profile, result);
  const accentColor = person === "partner" ? PERSON2_COLOR : PERSON1_COLOR;
  const accentBorder =
    person === "partner"
      ? "border-violet-500/25 bg-violet-500/[0.03]"
      : "border-primary/25 bg-primary/[0.03]";
  const offsetBounds = pillar3aWithdrawalOffsetBounds(
    result.bvgPensionStartAge,
    result.earliestWithdrawalAge,
    result.latestWithdrawalAge,
    PILLAR_3A_MIN_WITHDRAWAL_OFFSET,
    PILLAR_3A_MAX_WITHDRAWAL_OFFSET,
  );

  const body = (
    <>
      {displayAccounts.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          Keine 3a-Konten in den Stammdaten. Erfassen Sie Konten unter{" "}
          <a href="/master-data" className="text-primary underline">
            Stammdaten
          </a>
          .
        </p>
      ) : (
        displayAccounts.map((account) => {
            const item =
              overrideState[account.id] ??
              buildInitialPillar3aOverrides(profile, undefined, displayAccounts)[
                account.id
              ];
            const accountResult = result.accounts.find((a) => a.id === account.id);
            if (!item) return null;

            return (
              <div
                key={account.id}
                className={`space-y-3 rounded-lg border p-4 ${accentBorder}`}
              >
                <div className="flex flex-wrap items-center gap-2">
                  <h3 className="text-base font-semibold tracking-tight">
                    {account.name}
                  </h3>
                  {account.isAutoGenerated ? (
                    <Badge variant="secondary" className="text-xs">
                      Auto-Split
                    </Badge>
                  ) : null}
                </div>
                <p className="text-xs text-muted-foreground">
                  Stammdaten: Kapital {formatCHF(account.currentCapital)} ·
                  Einzahlung {formatCHF(account.annualContribution)}/J.
                  {accountResult
                    ? ` → Projektion ${formatCHF(accountResult.projectedCapital)}`
                    : ""}
                </p>

                <div className="grid gap-2">
                  <Label htmlFor={`3a-withdraw-${account.id}`}>
                    Jahre relativ zum BVG-Leistungsbeginn
                  </Label>
                  <WithdrawalOffsetInput
                    id={`3a-withdraw-${account.id}`}
                    value={item.withdrawalYearOffset}
                    legalBounds={offsetBounds}
                    onCommit={(offset) =>
                      onChange(account.id, { withdrawalYearOffset: offset })
                    }
                  />
                  <p className="text-xs text-muted-foreground">
                    0 = mit BVG · positiv = später gestaffelt · negativ = vor BVG ·
                    im Szenario zulässig {offsetBounds.min} bis {offsetBounds.max}
                    {accountResult?.isClamped ? " · Alter angepasst" : ""}
                  </p>
                </div>

                <OverrideRow
                  id={`3a-cap-${account.id}`}
                  checked={item.useCapitalOverride}
                  onCheckedChange={(v) =>
                    onChange(account.id, { useCapitalOverride: v })
                  }
                  label="Anderes Startkapital"
                >
                  <ChfInput
                    value={item.capitalOverride}
                    onChange={(v) =>
                      onChange(account.id, { capitalOverride: v })
                    }
                  />
                </OverrideRow>

                <OverrideRow
                  id={`3a-contrib-${account.id}`}
                  checked={item.useContributionOverride}
                  onCheckedChange={(v) =>
                    onChange(account.id, { useContributionOverride: v })
                  }
                  label="Andere jährliche Einzahlung"
                >
                  <ChfInput
                    value={item.contributionOverride}
                    onChange={(v) =>
                      onChange(account.id, { contributionOverride: v })
                    }
                  />
                </OverrideRow>

                <OverrideRow
                  id={`3a-return-${account.id}`}
                  checked={item.useReturnOverride}
                  onCheckedChange={(v) =>
                    onChange(account.id, { useReturnOverride: v })
                  }
                  label="Andere Rendite"
                >
                  <PercentInput
                    value={item.returnOverride}
                    onChange={(v) => onChange(account.id, { returnOverride: v })}
                  />
                </OverrideRow>
              </div>
            );
          })
        )}

        {result.scheduledWithdrawals.length > 0 ? (
          <div className="rounded-lg border bg-muted/20 p-4 text-xs space-y-1">
            <p className="font-medium text-sm">Geplanter 3a-Bezug</p>
            {result.scheduledWithdrawals.map((w) => (
              <p key={w.accountId} className="text-muted-foreground">
                {w.accountName}: {formatCHF(w.amount)} mit {w.withdrawalAge}{" "}
                Jahren (
                {w.yearOffset === 0
                  ? "mit BVG-Beginn"
                  : w.yearOffset < 0
                    ? `${Math.abs(w.yearOffset)} J. vor BVG`
                    : `${w.yearOffset} J. nach BVG`}
                )
              </p>
            ))}
            <p className="pt-1 text-muted-foreground">
              Total 3a → freies Vermögen:{" "}
              {formatCHF(result.totalProjectedCapital)}
            </p>
          </div>
        ) : null}
    </>
  );

  if (embedded) {
    return <div className="space-y-5">{body}</div>;
  }

  return (
    <CollapsibleCard
      title="Säule 3a"
      description={`Gestaffelter Bezug ins freie Vermögen: pro Konto Jahre relativ zum BVG-Leistungsbeginn (0 = mit BVG, +1 = ein Jahr später usw.). Frühestens ${result.earliestWithdrawalAge} J., gestaffelt bis ${result.latestWithdrawalAge} J.`}
      icon={<Landmark className="h-5 w-5" style={{ color: accentColor }} />}
    >
      <div className="space-y-5">{body}</div>
    </CollapsibleCard>
  );
}

function WithdrawalOffsetInput({
  id,
  value,
  legalBounds,
  onCommit,
}: {
  id: string;
  value: number;
  legalBounds: { min: number; max: number };
  onCommit: (offset: number) => void;
}) {
  const [draft, setDraft] = useState<string | null>(null);

  useEffect(() => {
    setDraft(null);
  }, [value]);

  const display = draft ?? String(value);

  const commitDraft = (raw: string) => {
    setDraft(null);
    const trimmed = raw.trim();
    if (trimmed === "" || trimmed === "-") {
      onCommit(clampPillar3aWithdrawalOffset(0, legalBounds));
      return;
    }
    const parsed = Number.parseInt(trimmed, 10);
    if (Number.isNaN(parsed)) return;
    onCommit(clampPillar3aWithdrawalOffset(parsed, legalBounds));
  };

  return (
    <div className="flex items-center gap-1">
      <Input
        id={id}
        type="text"
        inputMode="numeric"
        className="w-32 font-mono"
        value={display}
        onChange={(e) => {
          const next = e.target.value;
          if (!/^-?\d*$/.test(next)) return;
          setDraft(next);
        }}
        onBlur={() => {
          if (draft != null) commitDraft(draft);
        }}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            commitDraft(draft ?? String(value));
            (e.target as HTMLInputElement).blur();
          }
        }}
      />
      <StepperButtons
        label="Bezugsjahr-Offset"
        onUp={() =>
          onCommit(
            clampPillar3aWithdrawalOffset(value + 1, legalBounds),
          )
        }
        onDown={() =>
          onCommit(
            clampPillar3aWithdrawalOffset(value - 1, legalBounds),
          )
        }
        upDisabled={value >= legalBounds.max}
        downDisabled={value <= legalBounds.min}
      />
    </div>
  );
}

function OverrideRow({
  id,
  checked,
  onCheckedChange,
  label,
  children,
}: {
  id: string;
  checked: boolean;
  onCheckedChange: (v: boolean) => void;
  label: string;
  children?: React.ReactNode;
}) {
  return (
    <div className="space-y-2">
      <div className="flex flex-wrap items-center gap-3">
        <Checkbox
          id={id}
          checked={checked}
          onCheckedChange={(v) => onCheckedChange(v === true)}
        />
        <Label htmlFor={id} className="cursor-pointer font-normal text-sm">
          {label}
        </Label>
      </div>
      {checked && children ? <div className="ml-7">{children}</div> : null}
    </div>
  );
}

function ChfInput({
  value,
  onChange,
}: {
  value: string;
  onChange: (v: string) => void;
}) {
  return (
    <ChfStepperInput
      className="w-52"
      value={value}
      onChange={(e) => {
        const parsed = parseSwissNumber(e.target.value);
        onChange(formatSwissNumber(parsed));
      }}
      step={CHF_STEP.wealth}
      ariaLabel="3a Betrag"
    />
  );
}

function PercentInput({
  value,
  onChange,
}: {
  value: number;
  onChange: (v: number) => void;
}) {
  return (
    <PercentStepperNumberInput
      value={value}
      onChange={onChange}
      step={NUM_STEP.percentFine}
    />
  );
}
