/**
 * Säule 3a – Berechnungsmodul (mehrere Konten, gestaffelter Bezug)
 */

import {
  DEFAULT_ASSUMPTIONS,
  PILLAR_3A_MAX_CONTRIBUTION,
  PILLAR_3A_MAX_WITHDRAWAL_OFFSET,
  PILLAR_3A_MIN_WITHDRAWAL_OFFSET,
} from "../constants";
import {
  clampPillar3aWithdrawalOffset,
  getPillar3aEffectiveEarliestWithdrawalAge,
  getPillar3aLatestWithdrawalAge,
  pillar3aWithdrawalOffsetBounds,
  pillar3aYearOffsetFromBvgStart,
  resolvePillar3aWithdrawalAge,
  type PensionGender,
} from "../legal-ages";
import {
  simulatePillar3aAccounts,
  type Pillar3aAutoSplitSettings,
} from "@/lib/pillar3a/auto-split";
import { defaultWithdrawalSchedule } from "@/lib/pillar3a/accounts";
import {
  formatWorkloadReductions,
  type WorkloadReduction,
} from "../workload";
import { formatInflationRatePercent } from "../inflation";

export interface Pillar3aAccountInput {
  id: string;
  name: string;
  currentCapital: number;
  annualContribution: number;
  returnRate?: number;
  /** Jahre relativ zum BVG-Leistungsbeginn (negativ = vor BVG) */
  withdrawalYearOffset?: number;
  /** Optionales fixes Bezugsalter (überschreibt Offset) */
  withdrawalAgeOverride?: number | null;
}

export interface Pillar3aInput {
  birthDate: string;
  gender?: PensionGender | null;
  employmentEndAge: number;
  bvgPensionStartAge: number;
  ahvPensionStartAge: number;
  accounts: Pillar3aAccountInput[];
  autoSplit?: Pillar3aAutoSplitSettings;
  withdrawalSchedule?: Record<string, number>;
  /** Optionale feste Bezugsalter pro Konto (Szenario) */
  withdrawalAgeOverrides?: Record<string, number | null>;
  workloadReductions?: WorkloadReduction[];
  /** Annual inflation (decimal); contributions grow each projection year */
  inflationRate?: number;
}

export interface Pillar3aYearProjection {
  age: number;
  year: number;
  accountId: string;
  capitalStart: number;
  contribution: number;
  interest: number;
  capitalEnd: number;
}

export interface Pillar3aScheduledWithdrawal {
  yearOffset: number;
  amount: number;
  accountId: string;
  accountName: string;
  withdrawalAge: number;
  withdrawalYear: number;
  earliestLegalAge: number;
  latestLegalAge: number;
  isClamped: boolean;
}

export interface Pillar3aAccountResult {
  id: string;
  name: string;
  projectedCapital: number;
  withdrawalAmount: number;
  withdrawalYearOffset: number;
  withdrawalAge: number;
  withdrawalYear: number;
  earliestLegalAge: number;
  latestLegalAge: number;
  isClamped: boolean;
  annualContribution: number;
  returnRate: number;
  isAutoGenerated?: boolean;
  projection: Pillar3aYearProjection[];
}

export interface Pillar3aExplanationStep {
  label: string;
  value: string;
  detail?: string;
}

export interface Pillar3aResult {
  totalProjectedCapital: number;
  totalAnnualContribution: number;
  earliestWithdrawalAge: number;
  latestWithdrawalAge: number;
  bvgPensionStartAge: number;
  accounts: Pillar3aAccountResult[];
  scheduledWithdrawals: Pillar3aScheduledWithdrawal[];
  explanation: Pillar3aExplanationStep[];
}

function currentAgeFromBirthDate(birthDate: string): number {
  const birth = new Date(birthDate);
  const now = new Date();
  let age = now.getFullYear() - birth.getFullYear();
  const monthDiff = now.getMonth() - birth.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && now.getDate() < birth.getDate())) {
    age--;
  }
  return age;
}

function capitalAtWithdrawalAge(
  projection: Pillar3aYearProjection[],
  withdrawalAge: number,
  currentAge: number,
  fallbackCapital: number,
  returnRate: number,
): number {
  if (withdrawalAge <= currentAge) {
    return projection[0]?.capitalStart ?? fallbackCapital;
  }

  const priorAge = withdrawalAge - 1;
  const row = projection.find((p) => p.age === priorAge);
  if (row) return row.capitalEnd;

  if (projection.length === 0) return fallbackCapital;

  let capital = projection[projection.length - 1].capitalEnd;
  const lastAge = projection[projection.length - 1].age;

  for (let age = lastAge + 1; age < withdrawalAge; age++) {
    capital += Math.round(capital * returnRate);
  }

  return Math.round(capital);
}

export function calculatePillar3a(input: Pillar3aInput): Pillar3aResult {
  const {
    birthDate,
    gender,
    employmentEndAge,
    bvgPensionStartAge,
    ahvPensionStartAge,
    accounts,
    autoSplit,
    withdrawalSchedule,
    withdrawalAgeOverrides,
    workloadReductions = [],
    inflationRate = 0,
  } = input;
  const explanation: Pillar3aExplanationStep[] = [];
  const activeAccounts = accounts.length > 0 ? accounts : [];

  const earliestWithdrawalAge = getPillar3aEffectiveEarliestWithdrawalAge(
    birthDate,
    gender,
    employmentEndAge,
  );
  const latestWithdrawalAge = getPillar3aLatestWithdrawalAge(ahvPensionStartAge);

  if (activeAccounts.length === 0) {
    return {
      totalProjectedCapital: 0,
      totalAnnualContribution: 0,
      earliestWithdrawalAge,
      latestWithdrawalAge,
      bvgPensionStartAge,
      accounts: [],
      scheduledWithdrawals: [],
      explanation: [
        {
          label: "Säule 3a",
          value: "Keine Konten erfasst",
        },
      ],
    };
  }

  const currentAge = currentAgeFromBirthDate(birthDate);
  const startYear = new Date().getFullYear();
  const defaultReturn = DEFAULT_ASSUMPTIONS.returnRate3a;
  const offsetBounds = pillar3aWithdrawalOffsetBounds(
    bvgPensionStartAge,
    earliestWithdrawalAge,
    latestWithdrawalAge,
    PILLAR_3A_MIN_WITHDRAWAL_OFFSET,
    PILLAR_3A_MAX_WITHDRAWAL_OFFSET,
  );

  const scheduleOptions = {
    bvgPensionStartAge,
    earliestWithdrawalAge,
    latestWithdrawalAge,
  };

  const resolveWithdrawalAgeForOffset = (offset: number) =>
    resolvePillar3aWithdrawalAge(
      birthDate,
      gender,
      employmentEndAge,
      bvgPensionStartAge,
      ahvPensionStartAge,
      offset,
      null,
    );

  const provisionalSchedule = defaultWithdrawalSchedule(
    activeAccounts.map((a) => a.id),
    withdrawalSchedule,
    scheduleOptions,
  );

  let maxWithdrawalAge = employmentEndAge;
  for (const account of activeAccounts) {
    const offset = clampPillar3aWithdrawalOffset(
      provisionalSchedule[account.id] ?? 0,
      offsetBounds,
    );
    maxWithdrawalAge = Math.max(
      maxWithdrawalAge,
      resolveWithdrawalAgeForOffset(offset),
    );
  }

  let yearsToSimulate = Math.max(0, maxWithdrawalAge - currentAge);
  let simulated = simulatePillar3aAccounts(
    activeAccounts,
    autoSplit,
    yearsToSimulate,
    currentAge,
    startYear,
    defaultReturn,
    workloadReductions,
    employmentEndAge,
    undefined,
    undefined,
    inflationRate,
  );

  const schedule = defaultWithdrawalSchedule(
    simulated.map((a) => a.id),
    withdrawalSchedule,
    scheduleOptions,
  );

  const resolveWithdrawalAgeForAccount = (
    accountId: string,
    accountAnnualContribution: number,
  ) => {
    const withdrawalYearOffset = clampPillar3aWithdrawalOffset(
      schedule[accountId] ?? 0,
      offsetBounds,
    );
    const requestedAge = withdrawalAgeOverrides?.[accountId] ?? null;
    return resolvePillar3aWithdrawalAge(
      birthDate,
      gender,
      employmentEndAge,
      bvgPensionStartAge,
      ahvPensionStartAge,
      withdrawalYearOffset,
      requestedAge,
    );
  };

  let withdrawalAgesByAccount: Record<string, number> = {};
  for (const account of simulated) {
    withdrawalAgesByAccount[account.id] = resolveWithdrawalAgeForAccount(
      account.id,
      account.annualContribution,
    );
  }

  let contributionStopAge = Math.min(...Object.values(withdrawalAgesByAccount));
  if (!Number.isFinite(contributionStopAge)) {
    contributionStopAge = employmentEndAge;
  }

  let finalMaxWithdrawalAge = employmentEndAge;
  for (const age of Object.values(withdrawalAgesByAccount)) {
    finalMaxWithdrawalAge = Math.max(finalMaxWithdrawalAge, age);
  }

  if (finalMaxWithdrawalAge > maxWithdrawalAge) {
    yearsToSimulate = Math.max(0, finalMaxWithdrawalAge - currentAge);
  }

  simulated = simulatePillar3aAccounts(
    activeAccounts,
    autoSplit,
    yearsToSimulate,
    currentAge,
    startYear,
    defaultReturn,
    workloadReductions,
    employmentEndAge,
    contributionStopAge,
    withdrawalAgesByAccount,
    inflationRate,
  );

  // Auto-Split kann neue Konten erzeugen — Bezugsalter neu auflösen
  const finalSchedule = defaultWithdrawalSchedule(
    simulated.map((a) => a.id),
    withdrawalSchedule,
    scheduleOptions,
  );
  withdrawalAgesByAccount = {};
  for (const account of simulated) {
    const offset = clampPillar3aWithdrawalOffset(
      finalSchedule[account.id] ?? 0,
      offsetBounds,
    );
    withdrawalAgesByAccount[account.id] = resolvePillar3aWithdrawalAge(
      birthDate,
      gender,
      employmentEndAge,
      bvgPensionStartAge,
      ahvPensionStartAge,
      offset,
      withdrawalAgeOverrides?.[account.id] ?? null,
    );
  }
  contributionStopAge = Math.min(...Object.values(withdrawalAgesByAccount));
  if (!Number.isFinite(contributionStopAge)) {
    contributionStopAge = employmentEndAge;
  }

  simulated = simulatePillar3aAccounts(
    activeAccounts,
    autoSplit,
    yearsToSimulate,
    currentAge,
    startYear,
    defaultReturn,
    workloadReductions,
    employmentEndAge,
    contributionStopAge,
    withdrawalAgesByAccount,
    inflationRate,
  );

  maxWithdrawalAge = Math.max(...Object.values(withdrawalAgesByAccount));

  explanation.push({
    label: "Gesetzlicher 3a-Bezugsrahmen",
    value: `${earliestWithdrawalAge} – ${latestWithdrawalAge} Jahre`,
    detail:
      "Frühestens 5 J. vor AHV-Referenzalter · gestaffelt bis AHV-Bezug (unabhängig von früher Erwerbsaufgabe)",
  });

  if (workloadReductions.length > 0) {
    explanation.push({
      label: "Arbeitspensum-Reduktion",
      value: formatWorkloadReductions(workloadReductions),
      detail: "3a-Einzahlungen werden ab den Stichtagen proportional reduziert",
    });
  }

  if (inflationRate > 0) {
    explanation.push({
      label: "Inflation (Einzahlungen)",
      value: formatInflationRatePercent(inflationRate),
      detail: "Jährliche 3a-Beiträge steigen bis zum Einzahlungsstopp",
    });
  }

  explanation.push({
    label: "Einzahlungsstopp",
    value: `ab ${contributionStopAge} Jahren`,
    detail:
      "Ab erstem 3a-Kapitalbezug entfallen Einzahlungen auf alle Konten; Rest verzinst sich nur noch",
  });

  if (autoSplit?.enabled && autoSplit.threshold > 0) {
    explanation.push({
      label: "Auto-Split",
      value: `ab CHF ${Math.round(autoSplit.threshold).toLocaleString("de-CH")}`,
      detail: `Neues Konto mit ${autoSplit.contributionMode === "max" ? "max. Einzahlung" : "Satz Vorgänger-Konto"}`,
    });
  }

  explanation.push({
    label: "Anzahl 3a-Konten (projiziert)",
    value: `${simulated.length}`,
    detail:
      simulated.some((a) => a.isAutoGenerated)
        ? `${simulated.filter((a) => !a.isAutoGenerated).length} erfasst + ${simulated.filter((a) => a.isAutoGenerated).length} automatisch`
        : "Gestaffelter Bezug über Bezugsjahr pro Konto",
  });

  const totalAnnualContribution = simulated.reduce(
    (sum, a) => sum + Math.max(0, a.annualContribution),
    0,
  );

  explanation.push({
    label: "Jährliche Einzahlungen (total)",
    value: `CHF ${Math.round(totalAnnualContribution).toLocaleString("de-CH")}`,
    detail: `Max. empfohlen CHF ${PILLAR_3A_MAX_CONTRIBUTION.toLocaleString("de-CH")}/Jahr (mit PK)`,
  });

  const accountResults: Pillar3aAccountResult[] = [];
  const scheduledWithdrawals: Pillar3aScheduledWithdrawal[] = [];

  simulated.forEach((account) => {
    const withdrawalYearOffset = clampPillar3aWithdrawalOffset(
      finalSchedule[account.id] ?? 0,
      offsetBounds,
    );
    const requestedAge = withdrawalAgeOverrides?.[account.id] ?? null;

    const rawPlannedAge =
      requestedAge != null
        ? requestedAge
        : bvgPensionStartAge + withdrawalYearOffset;

    const withdrawalAge = resolvePillar3aWithdrawalAge(
      birthDate,
      gender,
      employmentEndAge,
      bvgPensionStartAge,
      ahvPensionStartAge,
      withdrawalYearOffset,
      requestedAge,
    );

    const isClamped = withdrawalAge !== rawPlannedAge;
    const yearOffset = pillar3aYearOffsetFromBvgStart(
      withdrawalAge,
      bvgPensionStartAge,
    );
    const projectedCapital = capitalAtWithdrawalAge(
      account.projection,
      withdrawalAge,
      currentAge,
      account.projectedCapital,
      account.returnRate,
    );
    const withdrawalYear = startYear + Math.max(0, withdrawalAge - currentAge);

    accountResults.push({
      id: account.id,
      name: account.name,
      projectedCapital,
      withdrawalAmount: projectedCapital,
      withdrawalYearOffset: yearOffset,
      withdrawalAge,
      withdrawalYear,
      earliestLegalAge: earliestWithdrawalAge,
      latestLegalAge: latestWithdrawalAge,
      isClamped,
      annualContribution: account.annualContribution,
      returnRate: account.returnRate,
      isAutoGenerated: account.isAutoGenerated,
      projection: account.projection,
    });

    scheduledWithdrawals.push({
      yearOffset,
      amount: projectedCapital,
      accountId: account.id,
      accountName: account.name,
      withdrawalAge,
      withdrawalYear,
      earliestLegalAge: earliestWithdrawalAge,
      latestLegalAge: latestWithdrawalAge,
      isClamped,
    });

    explanation.push({
      label: account.name,
      value: `CHF ${projectedCapital.toLocaleString("de-CH")}`,
      detail: [
        account.isAutoGenerated ? "Automatisch eröffnet" : null,
        `Einzahlung CHF ${Math.round(account.annualContribution).toLocaleString("de-CH")}/J.`,
        `Bezug mit ${withdrawalAge} Jahren${isClamped ? " (gesetzlich angepasst)" : ""}`,
        yearOffset === 0
          ? "im Jahr des BVG-Beginns"
          : yearOffset < 0
            ? `${Math.abs(yearOffset)} J. vor BVG-Beginn`
            : `${yearOffset} J. nach BVG-Beginn`,
      ]
        .filter(Boolean)
        .join(" · "),
    });
  });

  scheduledWithdrawals.sort(
    (a, b) => a.withdrawalAge - b.withdrawalAge || a.yearOffset - b.yearOffset,
  );

  const totalProjectedCapital = accountResults.reduce(
    (sum, a) => sum + a.projectedCapital,
    0,
  );

  explanation.push({
    label: "Total projiziertes 3a-Kapital",
    value: `CHF ${totalProjectedCapital.toLocaleString("de-CH")}`,
    detail: "Fliesst gestaffelt ins freie Vermögen",
  });

  return {
    totalProjectedCapital,
    totalAnnualContribution,
    earliestWithdrawalAge,
    latestWithdrawalAge,
    bvgPensionStartAge,
    accounts: accountResults,
    scheduledWithdrawals,
    explanation,
  };
}
