import { PILLAR_3A_MAX_ACCOUNTS, PILLAR_3A_MAX_CONTRIBUTION } from "@/lib/engine/constants";
import { inflateAmount } from "@/lib/engine/inflation";
import type {
  Pillar3aAccountInput,
  Pillar3aYearProjection,
} from "@/lib/engine/modules/pillar3a";
import {
  type WorkloadReduction,
  workloadFactorAtAge,
} from "@/lib/engine/workload";
import { parseDbAmount } from "@/lib/format/db-numbers";

export type Pillar3aAutoSplitSettings = {
  enabled: boolean;
  threshold: number;
  contributionMode: "max" | "last";
  namePrefix: string;
};

export type SimulatedPillar3aAccount = {
  id: string;
  name: string;
  projectedCapital: number;
  annualContribution: number;
  returnRate: number;
  isAutoGenerated: boolean;
  projection: Pillar3aYearProjection[];
};

type SimAccount = {
  id: string;
  name: string;
  capital: number;
  annualContribution: number;
  returnRate: number;
  receivesContributions: boolean;
  isAutoGenerated: boolean;
  projection: Pillar3aYearProjection[];
};

function projectAccountsIndependently(
  accounts: Pillar3aAccountInput[],
  yearsToRetirement: number,
  currentAge: number,
  startYear: number,
  defaultReturnRate: number,
  workloadReductions: WorkloadReduction[] = [],
  employmentEndAge?: number,
  contributionStopAge?: number,
  withdrawalAgesByAccount?: Record<string, number>,
  inflationRate = 0,
): SimulatedPillar3aAccount[] {
  return accounts.map((account) => {
    const returnRate = account.returnRate ?? defaultReturnRate;
    const baseContribution = Math.max(0, parseDbAmount(account.annualContribution));
    const withdrawalAge = withdrawalAgesByAccount?.[account.id];
    const projection: Pillar3aYearProjection[] = [];
    let capital = Math.max(0, parseDbAmount(account.currentCapital));

    for (let i = 0; i < yearsToRetirement; i++) {
      const age = currentAge + i;
      const year = startYear + i;
      const capitalStart = capital;

      if (withdrawalAge != null && age >= withdrawalAge) {
        projection.push({
          age,
          year,
          accountId: account.id,
          capitalStart: Math.round(capitalStart),
          contribution: 0,
          interest: 0,
          capitalEnd: 0,
        });
        capital = 0;
        continue;
      }

      const stillEmployed =
        employmentEndAge == null ? true : age < employmentEndAge;
      const contributionsAllowed =
        contributionStopAge == null || age < contributionStopAge;
      const workload = workloadFactorAtAge(workloadReductions, age);
      const yearContributionBase = inflateAmount(
        baseContribution,
        inflationRate,
        i,
      );
      const contribution =
        stillEmployed && contributionsAllowed
          ? Math.round(yearContributionBase * workload)
          : 0;
      const interest = Math.round((capitalStart + contribution / 2) * returnRate);
      capital = capitalStart + contribution + interest;
      projection.push({
        age,
        year,
        accountId: account.id,
        capitalStart: Math.round(capitalStart),
        contribution,
        interest,
        capitalEnd: Math.round(capital),
      });
    }

    return {
      id: account.id,
      name: account.name,
      projectedCapital: Math.round(capital),
      annualContribution: baseContribution,
      returnRate,
      isAutoGenerated: false,
      projection,
    };
  });
}

function contributionForNewAccount(
  mode: "max" | "last",
  lastContribution: number,
  activeContributions: number[],
  yearIndex: number,
  inflationRate: number,
): number {
  const inflatedLast = inflateAmount(lastContribution, inflationRate, yearIndex);
  if (mode === "last") {
    return Math.max(0, inflatedLast);
  }
  const maxAtYear = inflateAmount(
    PILLAR_3A_MAX_CONTRIBUTION,
    inflationRate,
    yearIndex,
  );
  const used = activeContributions.reduce((sum, v) => sum + Math.max(0, v), 0);
  return Math.max(0, maxAtYear - used);
}

export function simulatePillar3aAccounts(
  inputAccounts: Pillar3aAccountInput[],
  autoSplit: Pillar3aAutoSplitSettings | undefined,
  yearsToRetirement: number,
  currentAge: number,
  startYear: number,
  defaultReturnRate: number,
  workloadReductions: WorkloadReduction[] = [],
  employmentEndAge?: number,
  contributionStopAge?: number,
  withdrawalAgesByAccount?: Record<string, number>,
  inflationRate = 0,
): SimulatedPillar3aAccount[] {
  if (inputAccounts.length === 0 || yearsToRetirement <= 0) {
    return projectAccountsIndependently(
      inputAccounts,
      yearsToRetirement,
      currentAge,
      startYear,
      defaultReturnRate,
      workloadReductions,
      employmentEndAge,
      contributionStopAge,
      withdrawalAgesByAccount,
      inflationRate,
    );
  }

  if (!autoSplit?.enabled || autoSplit.threshold <= 0) {
    return projectAccountsIndependently(
      inputAccounts,
      yearsToRetirement,
      currentAge,
      startYear,
      defaultReturnRate,
      workloadReductions,
      employmentEndAge,
      contributionStopAge,
      withdrawalAgesByAccount,
      inflationRate,
    );
  }

  const prefix = autoSplit.namePrefix.trim() || "3a-Konto";
  let accounts: SimAccount[] = inputAccounts.map((account) => ({
    id: account.id,
    name: account.name,
    capital: Math.max(0, parseDbAmount(account.currentCapital)),
    annualContribution: Math.max(0, parseDbAmount(account.annualContribution)),
    returnRate: account.returnRate ?? defaultReturnRate,
    receivesContributions: parseDbAmount(account.annualContribution) > 0,
    isAutoGenerated: false,
    projection: [],
  }));

  for (let i = 0; i < yearsToRetirement; i++) {
    const age = currentAge + i;
    const year = startYear + i;
    const stillEmployed =
      employmentEndAge == null ? true : age < employmentEndAge;
    const contributionsAllowed =
      contributionStopAge == null || age < contributionStopAge;
    const workload = workloadFactorAtAge(workloadReductions, age);

    for (const account of accounts) {
      const withdrawalAge = withdrawalAgesByAccount?.[account.id];
      const capitalStart = account.capital;

      if (withdrawalAge != null && age >= withdrawalAge) {
        account.capital = 0;
        account.projection.push({
          age,
          year,
          accountId: account.id,
          capitalStart: Math.round(capitalStart),
          contribution: 0,
          interest: 0,
          capitalEnd: 0,
        });
        continue;
      }

      const yearContributionBase = inflateAmount(
        account.annualContribution,
        inflationRate,
        i,
      );
      const contribution =
        stillEmployed && contributionsAllowed && account.receivesContributions
          ? Math.round(yearContributionBase * workload)
          : 0;
      const interest = Math.round(
        (capitalStart + contribution / 2) * account.returnRate,
      );
      account.capital = capitalStart + contribution + interest;
      account.projection.push({
        age,
        year,
        accountId: account.id,
        capitalStart: Math.round(capitalStart),
        contribution,
        interest,
        capitalEnd: Math.round(account.capital),
      });
    }

    if (!contributionsAllowed || accounts.length >= PILLAR_3A_MAX_ACCOUNTS) continue;

    const toSplit = accounts.filter(
      (account) =>
        account.receivesContributions &&
        account.capital >= autoSplit.threshold,
    );

    for (const account of toSplit) {
      if (accounts.length >= PILLAR_3A_MAX_ACCOUNTS) break;

      account.receivesContributions = false;
      const activeContributions = accounts
        .filter((a) => a.receivesContributions)
        .map((a) => inflateAmount(a.annualContribution, inflationRate, i));
      const newContribution = contributionForNewAccount(
        autoSplit.contributionMode,
        account.annualContribution,
        activeContributions,
        i,
        inflationRate,
      );
      const autoNumber =
        accounts.filter((a) => a.isAutoGenerated).length + 1;
      accounts.push({
        id: `auto-split-${accounts.length}-${autoNumber}`,
        name: `${prefix} ${accounts.length + 1}`,
        capital: 0,
        annualContribution: newContribution,
        returnRate: account.returnRate,
        receivesContributions: newContribution > 0,
        isAutoGenerated: true,
        projection: [],
      });
    }
  }

  return accounts.map((account) => ({
    id: account.id,
    name: account.name,
    projectedCapital: Math.round(account.capital),
    annualContribution: account.receivesContributions
      ? account.annualContribution
      : account.projection.some((p) => p.contribution > 0)
        ? Math.max(...account.projection.map((p) => p.contribution))
        : account.annualContribution,
    returnRate: account.returnRate,
    isAutoGenerated: account.isAutoGenerated,
    projection: account.projection,
  }));
}

export function maxTotalContributionHint(accounts: SimulatedPillar3aAccount[]): number {
  const total = accounts.reduce((sum, a) => sum + a.annualContribution, 0);
  return total > PILLAR_3A_MAX_CONTRIBUTION ? total : 0;
}
